//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private string CityField;
        
        private string CountryField;
        
        private string DescriptionField;
        
        private string IdField;
        
        private string[] ImageListField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private string NameField;
        
        private int RatingField;
        
        private HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Review[] ReviewsField;
        
        private string StateCodeField;
        
        private System.DateTime UtcTimeSubmittedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ImageList
        {
            get
            {
                return this.ImageListField;
            }
            set
            {
                this.ImageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Review[] Reviews
        {
            get
            {
                return this.ReviewsField;
            }
            set
            {
                this.ReviewsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateCode
        {
            get
            {
                return this.StateCodeField;
            }
            set
            {
                this.StateCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UtcTimeSubmitted
        {
            get
            {
                return this.UtcTimeSubmittedField;
            }
            set
            {
                this.UtcTimeSubmittedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CleanlinessField;
        
        private string DescriptionField;
        
        private string HotelIdField;
        
        private string IdField;
        
        private int LocationField;
        
        private int RatingField;
        
        private int RoomsField;
        
        private int ServiceField;
        
        private string TitleField;
        
        private string UserNameField;
        
        private System.DateTime UtcTimeSubmittedField;
        
        private int ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cleanliness
        {
            get
            {
                return this.CleanlinessField;
            }
            set
            {
                this.CleanlinessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelId
        {
            get
            {
                return this.HotelIdField;
            }
            set
            {
                this.HotelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rooms
        {
            get
            {
                return this.RoomsField;
            }
            set
            {
                this.RoomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UtcTimeSubmitted
        {
            get
            {
                return this.UtcTimeSubmittedField;
            }
            set
            {
                this.UtcTimeSubmittedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelModelForIntermediatePage", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
    public partial class HotelModelForIntermediatePage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private string CityField;
        
        private string CountryField;
        
        private string HotelIdField;
        
        private string ImageField;
        
        private string NameField;
        
        private int RatingField;
        
        private string StateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelId
        {
            get
            {
                return this.HotelIdField;
            }
            set
            {
                this.HotelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterNullException", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
    public partial class ParameterNullException : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FaultIdField;
        
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FaultId
        {
            get
            {
                return this.FaultIdField;
            }
            set
            {
                this.FaultIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelDoesNotExistFault", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
    public partial class HotelDoesNotExistFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FaultIdField;
        
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FaultId
        {
            get
            {
                return this.FaultIdField;
            }
            set
            {
                this.FaultIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFaults", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
    public partial class CustomFaults : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FaultCodeField;
        
        private string FaultMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FaultCode
        {
            get
            {
                return this.FaultCodeField;
            }
            set
            {
                this.FaultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage
        {
            get
            {
                return this.FaultMessageField;
            }
            set
            {
                this.FaultMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReviewDoesNotExistFault", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
    public partial class ReviewDoesNotExistFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FaultIdField;
        
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FaultId
        {
            get
            {
                return this.FaultIdField;
            }
            set
            {
                this.FaultIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.IHotelsAdvisor")]
    public interface IHotelsAdvisor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/GetHotelById", ReplyAction="http://tempuri.org/IHotelsAdvisor/GetHotelByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.ParameterNullException), Action="http://tempuri.org/IHotelsAdvisor/GetHotelByIdParameterNullExceptionFault", Name="ParameterNullException", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.HotelDoesNotExistFault), Action="http://tempuri.org/IHotelsAdvisor/GetHotelByIdHotelDoesNotExistFaultFault", Name="HotelDoesNotExistFault", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
        HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Hotel GetHotelById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/GetHotelById", ReplyAction="http://tempuri.org/IHotelsAdvisor/GetHotelByIdResponse")]
        System.Threading.Tasks.Task<HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Hotel> GetHotelByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/AddReview", ReplyAction="http://tempuri.org/IHotelsAdvisor/AddReviewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.CustomFaults), Action="http://tempuri.org/IHotelsAdvisor/AddReviewCustomFaultsFault", Name="CustomFaults", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
        bool AddReview(string hotelId, HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Review review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/AddReview", ReplyAction="http://tempuri.org/IHotelsAdvisor/AddReviewResponse")]
        System.Threading.Tasks.Task<bool> AddReviewAsync(string hotelId, HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Review review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/FetchHotelsByIdList", ReplyAction="http://tempuri.org/IHotelsAdvisor/FetchHotelsByIdListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.CustomFaults), Action="http://tempuri.org/IHotelsAdvisor/FetchHotelsByIdListCustomFaultsFault", Name="CustomFaults", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
        HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.HotelModelForIntermediatePage[] FetchHotelsByIdList(string[] hotelIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/FetchHotelsByIdList", ReplyAction="http://tempuri.org/IHotelsAdvisor/FetchHotelsByIdListResponse")]
        System.Threading.Tasks.Task<HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.HotelModelForIntermediatePage[]> FetchHotelsByIdListAsync(string[] hotelIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/GetTopHotels", ReplyAction="http://tempuri.org/IHotelsAdvisor/GetTopHotelsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.CustomFaults), Action="http://tempuri.org/IHotelsAdvisor/GetTopHotelsCustomFaultsFault", Name="CustomFaults", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
        HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Hotel[] GetTopHotels(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/GetTopHotels", ReplyAction="http://tempuri.org/IHotelsAdvisor/GetTopHotelsResponse")]
        System.Threading.Tasks.Task<HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Hotel[]> GetTopHotelsAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/DeleteReview", ReplyAction="http://tempuri.org/IHotelsAdvisor/DeleteReviewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.HotelDoesNotExistFault), Action="http://tempuri.org/IHotelsAdvisor/DeleteReviewHotelDoesNotExistFaultFault", Name="HotelDoesNotExistFault", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.ParameterNullException), Action="http://tempuri.org/IHotelsAdvisor/DeleteReviewParameterNullExceptionFault", Name="ParameterNullException", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
        bool DeleteReview(string reviewId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/DeleteReview", ReplyAction="http://tempuri.org/IHotelsAdvisor/DeleteReviewResponse")]
        System.Threading.Tasks.Task<bool> DeleteReviewAsync(string reviewId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/UpdateReview", ReplyAction="http://tempuri.org/IHotelsAdvisor/UpdateReviewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.ParameterNullException), Action="http://tempuri.org/IHotelsAdvisor/UpdateReviewParameterNullExceptionFault", Name="ParameterNullException", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.ReviewDoesNotExistFault), Action="http://tempuri.org/IHotelsAdvisor/UpdateReviewReviewDoesNotExistFaultFault", Name="ReviewDoesNotExistFault", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.HotelDoesNotExistFault), Action="http://tempuri.org/IHotelsAdvisor/UpdateReviewHotelDoesNotExistFaultFault", Name="HotelDoesNotExistFault", Namespace="http://schemas.datacontract.org/2004/07/HotelAdvisor.Services.DataContracts")]
        bool UpdateReview(string hotelId, HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Review review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelsAdvisor/UpdateReview", ReplyAction="http://tempuri.org/IHotelsAdvisor/UpdateReviewResponse")]
        System.Threading.Tasks.Task<bool> UpdateReviewAsync(string hotelId, HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Review review);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelsAdvisorChannel : HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.IHotelsAdvisor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelsAdvisorClient : System.ServiceModel.ClientBase<HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.IHotelsAdvisor>, HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.IHotelsAdvisor
    {
        
        public HotelsAdvisorClient()
        {
        }
        
        public HotelsAdvisorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public HotelsAdvisorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HotelsAdvisorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HotelsAdvisorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Hotel GetHotelById(string id)
        {
            return base.Channel.GetHotelById(id);
        }
        
        public System.Threading.Tasks.Task<HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Hotel> GetHotelByIdAsync(string id)
        {
            return base.Channel.GetHotelByIdAsync(id);
        }
        
        public bool AddReview(string hotelId, HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Review review)
        {
            return base.Channel.AddReview(hotelId, review);
        }
        
        public System.Threading.Tasks.Task<bool> AddReviewAsync(string hotelId, HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Review review)
        {
            return base.Channel.AddReviewAsync(hotelId, review);
        }
        
        public HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.HotelModelForIntermediatePage[] FetchHotelsByIdList(string[] hotelIds)
        {
            return base.Channel.FetchHotelsByIdList(hotelIds);
        }
        
        public System.Threading.Tasks.Task<HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.HotelModelForIntermediatePage[]> FetchHotelsByIdListAsync(string[] hotelIds)
        {
            return base.Channel.FetchHotelsByIdListAsync(hotelIds);
        }
        
        public HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Hotel[] GetTopHotels(int number)
        {
            return base.Channel.GetTopHotels(number);
        }
        
        public System.Threading.Tasks.Task<HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Hotel[]> GetTopHotelsAsync(int number)
        {
            return base.Channel.GetTopHotelsAsync(number);
        }
        
        public bool DeleteReview(string reviewId)
        {
            return base.Channel.DeleteReview(reviewId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteReviewAsync(string reviewId)
        {
            return base.Channel.DeleteReviewAsync(reviewId);
        }
        
        public bool UpdateReview(string hotelId, HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Review review)
        {
            return base.Channel.UpdateReview(hotelId, review);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateReviewAsync(string hotelId, HotelsAdvisorServiceFixtures.HotelsAdvisorService.Proxy.Review review)
        {
            return base.Channel.UpdateReviewAsync(hotelId, review);
        }
    }
}
